Repository e-Spirit/fsxa-api, pull requests merged in 2021-06, with the labels that each got.

#26 fix(express.ts): fix the body request locale error message
  src/integrations/express.ts
Labels: ready for release

#28 fix(express.ts): fix the deprecated express method
  src/integrations/express.ts
Labels: ready for release

#31 added npm install line in readme.md for the dev folder
  dev/README.md
  dev/index.ts
Labels: ready for release

#32 Tng 978
  src/__tests__/modules/QueryBuilder.spec.ts
  src/modules/QueryBuilder.ts
Labels: bug, ready for release

#30 feat: enabled usage of remote media
  .gitignore
  README.md
  dev/index.ts
  dev/utils.ts
  package-lock.json
  package.json
  src/__tests__/integrations/express.spec.ts
  src/__tests__/modules/FSXAApi.spec.ts
  src/integrations/express.ts
  src/modules/CaaSMapper.ts
  src/modules/FSXAApi.ts
  src/routes.ts
  src/types.ts
  src/utils.ts
Labels: enhancement, ready for release
